### PR TITLE
MNT: Re-rendered with conda-smithy 3.1.10 and pinning 2018.08.05 and added Python 3.7

### PR DESCRIPTION
**Pull request by jetuk**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

I've manually added the config for 3.7

### CODE REVIEW

**Comment by bluescarni** [comment]
@jetuk Thanks for the PR!

I think that the Python 3.7 builds are failing because the NLopt dependency is pulling in a Python dependency, and the NLopt feedstock has not been updated to 3.7 yet. I'll try to open a PR for the nlopt feedstock later today and see how that goes.

**Comment by jetuk** [comment]
OK thanks. Don't worry too much. I've figured out my build is mostly working because of packages from defaults rather than conda-forge. It just appears pygmo is the only one that is either not noarch or in defaults. 

I started with the assumption that many of the conda-forge builds were 3.7 compatible but that's not generally the case. So you could just wait for the conda-forge to roll it out themselves.

**Comment by jetuk** [comment]
@bluescarni I tried to update this again. Sorry it's a bit of a mess now. 

Seems like the 3.7 build is failing on OSX with a seg fault! But the others are working fine.

Is this PR still useful?

**Comment by bluescarni** [comment]
It's definitely useful, but I have no clue on why it would segfault on that particular setup :( Perhaps @darioizzo could help debugging this, as I don't have access to any OSX machine.

On a related note, are you following the recent conda-forge migration effort to new compiler/tools and updated python as well? Unfortunately I have not clearly understood what it entails, but I was wondering if you are aware of it and if this PR is related to it in any shape or form.

**Comment by jetuk** [comment]
Only very vaguely. I need to do some work to my own conda recipes and CI. My current project has its own conda channel. I probably need to submit it to conda-forge and do the recipes with the new toolchains.

**Comment by bluescarni** [comment]
@jetuk it seems like the conda bot automatically opened #25 (where we also have a segfault on OSX, to be investigated). Is it ok if I close your PR, or is there something from here we should port over the other PR?

**Comment by jetuk** [comment]
Yes I guess it can be closed.

**Pull request closed without merging**
