### PR TITLE
Pybind11 pin

### PR DESCRIPTION
**Pull request by darioizzo**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by darioizzo** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@darioizzo could you also try enabling C++17 builds for Windows, OSX and Linux? If I recall correctly, they were disabled on some platforms due to pybind11 bugs, but I think they might work now with the pinned commit.

**Comment by darioizzo** [comment]
@bluescarni I think the builds were c++17 already now for linux and win. I had removed the c++14 standard for OSX already. Let me know.

**Comment by bluescarni** [comment]
@darioizzo I think you removed the setting of the ``CPP_STANDARD`` variable altogether. Can you just make sure that now ``-DCMAKE_CXX_STANDARD=17`` is passed into pygmo's cmake invocation in ``build.sh`` regardless of whether we are on OSX or not?

**Comment by darioizzo** [comment]
@bluescarni OK. Now explicit.

**Comment by bluescarni** [comment]
@darioizzo can you remove the stray ``-DCMAKE_CXX_STANDARD=$CPP_STANDARD`` in the build script?

**Comment by bluescarni** [comment]
We need to change the install path of pybind11 in the Windows build. I'll give it a go.

**Comment by bluescarni** [comment]
@darioizzo perhaps you want to adapt the audi, dcgp recipes for Windows in the same manner.

**Pull request merged**
