### PR TITLE
Recipe improvements

### PR DESCRIPTION
**Pull request by bluescarni**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@isuruf any idea why only on OSX we get those warnings about transitive dependencies not being explicitly added in the ``run`` requirements?

Take for instance ``tbb``, this is a private dependency of ``pagmo`` (in the sense that the public pagmo API does not make any reference to anything ``tbb``-related, i.e., all the ``tbb`` usages in pagmo are within the .cpp files of the pagmo library). Thus, the ``pygmo`` module does not need to directly link to ``tbb``, it will link to ``libpagmo.so`` which in turn links to ``libtbb.so``.

The build process on OSX however seems to require that ``tbb`` is explicitly added as a ``run`` dependency, but there's no such warning on the Linux/Windows builds. Is this some difference in how the OSX linker works? Should we care about these warnings?

**Comment by isuruf** [comment]
@mingwandroid, is this a bug in conda-build?

**Comment by mingwandroid** [comment]
Transitive deps are never reported. TBB will be linked to whatever conda-build says it's linked to. If you don't want it linked to that then you probably need to take steps to figure out why it is being linked.

**Comment by mingwandroid** [comment]
Saying something's private doesn't mean that the build system will make it so.

**Comment by bluescarni** [comment]
> Saying something's private doesn't mean that the build system will make it so.

@mingwandroid would you mind elaborating a bit? Are you referring to the use of ``PRIVATE``, ``PUBLIC``, etc. attributes when using the ``target_link_libraries()`` command in CMake?

I think we do some overlinking in our project (``pagmo``) at the build level. For instance, regarding ``tbb``, in the current conda package ``tbb`` is linked with the ``PUBLIC`` option when creating ``libpagmo``, even though ``tbb`` is not part of the public API (all its uses are limited to the ``.cpp`` files of the library). I have a fix for this in https://github.com/esa/pagmo2/pull/373 , which makes the ``tbb`` dependency ``PRIVATE``.

In case of ``nlopt`` and ``ipopt``, however, we do include some of their headers in the public API, although what we need from those headers are only some type definitions. Thus, in the ``pagmo`` build system, the ``nlopt`` and ``ipopt`` targets (which include the compiled libraries for ``nlopt`` and ``ipopt``) are linked to ``libpagmo`` as ``PUBLIC`` dependencies.

Would you recommend us to create separate targets in CMake for the headers and the compiled components of ``ipopt`` and ``nlopt``, so that we have a public dependency on the headers but only a private one on the compile components?

And, last question, why is it that the conda build process in Linux/Windows is apparently able to determine and resolve the overlinking while that does not happen in OSX?

**Comment by mingwandroid** [comment]
It is simply a requirement that any dso auto-loaded by any other dso or exe is declared as a direct dependency of the package correctly. This prevents conda from either not installing it or uninstalling it even it is needed. Ignore that you may consider it to be provided transitively. That could change when transitive deps change.

I'm not going to bring cmake into it because it's a completely general point and it applies to all build systems.

The use our non use of headers is irrelevant to this too because this refers to low level machine code and elf linking. Including a header does not immediately confer a need to also link a library. It could be header only or no functions could get called from that header.

**Comment by bluescarni** [comment]
> It is simply a requirement that any dso auto-loaded by any other dso or exe is declared as a direct dependency of the package correctly.

Just to be clear, are you saying that if:

- library B depends on library A, and
- library C depends on library B,

then the recipe for C **always** needs to list A as a dependency? Or have I misunderstood your point?

Also, the fact that a dso is auto-loaded or not also depends on the current OS and compilation flags used (some of which are forced by the conda build process, as I understand). Does this mean that I need to make my dependencies in the recipe conditional on the OS?

**Comment by mingwandroid** [comment]
No, I am saying the direct opposite of that and it is really simple. Declare what you use directly, do not declare anything you do not used directly (unless you depend on things in the package other than DSOs). DSO autoloading works consistently across all OSes. Can you explain what you think is different?

Compilation flags do not come into it either. Why would they? Yes that's how you link to DSOs in general, but that's just an implementation detail. At this level I'm checking machine code binaries for sanity and making sure unnecessary packages are not pulled in. Nothing more.

I really believe you are overthinking this stuff.

**Comment by mingwandroid** [comment]
You never declare transitive dependencies. Why would you? We know about them already by walking the tree of dependencies.

However here you have a DSO that is being used transitively, but actually, it's also being used directly.

You have 2 choices here:

1. Fix your build system implementation so that the thing that's being linked directly is not linked directly.
2. Add the package containing the "should be transitive only but isn't" as a direct dependency. This is not ideal as you don't actually call anything from it directly.

**Comment by bluescarni** [comment]
@mingwandroid Thanks a lot for the explanation. We are working towards removing the overlinking upstream, I'll merge this PR despite the current warnings on OSX in preparation for the next version.

**Pull request merged**
