### PR TITLE
Tentative boost fixes.

### PR DESCRIPTION
**Pull request by bluescarni**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@xhochy any idea why there's a dependency conflict between Boost 1.70 and Boost 1.68 in Windows and OSX?

**Comment by xhochy** [comment]
@bluescarni Not really, https://ci.appveyor.com/project/conda-forge/pagmo-feedstock/branch/master was uploaded successfully and thus it should not give a conflict.

**Comment by xhochy** [comment]
There is some discussion about the conda-forge mirror currently not updating. Best thing is probably to retry this in ~12h.

**Comment by bluescarni** [comment]
@xhochy Ok, thanks a lot for looking into this!

**Pull request merged**
